package com.example.ewalletexample.Symbol;

public enum  Symbol {
    BASE_ADDRESS("192.168.15.113"),

    REASION_VERIFY("REASONVERIFY"),
    REASON_VERIFY_FOR_FORGET("FORGETPASSWORD"),
    REASON_VERIFY_FOR_REGISTER("REGISTER"),

    VERRIFY_FORGET("VERIFY_FORGET"),
    VERIFY_FORGET_BY_PHONE("PHONE"),
    VERIFY_FORGET_BY_EMAIL("EMAIL"),

    USER("USER"),
    FULLNAME("FULLNAME"),
    PASSWORD("PASSWORD"),
    PHONE("PHONE"),
    EMAIL("EMAIL"),
    USER_ID("USER_ID"),
    ADDRESS("ADDRESS"),
    CMND("CMND"),
    DOB("DATE_OF_BIRTH"),
    NUM_CARD_CONNECT_BANK("NUM_CARD"),
    BANK_CODE("BANK_CODE"),

    CHANGE_BALANCE("CHANGE_BALANCE"),

    MOBILE_CODE("MOBILE_CODE"),
    MOBILE_AMOUNT("MOBILE_AMOUNT"),

    USER_SEARCH_MODEL("USER_SEARCH_MODEL"),

    AMOUNT("AMOUNT"),
    IMAGE_ACCOUNT_LINK("IMAGE_ACCOUNT"),

    SOURCE_OF_FUND("SOURCE_OF_FUND"),
    SERVICE_TYPE("SERVICE_TYPE"),
    FEE_TRANSACTION("FEE"),
    AMOUNT_TRANSACTION("AMOUNT_TRANSACTION"),
    RECEIVER_PHONE("RECEIVER_PHONE"),
    RECEIVER_FULL_NAME("RECEIVER_FULL_NAME"),
    BANK_INFO("BANK_INFO"),

    CHILD_NAME_USERS_FIREBASE_DATABASE("users"),
    CHILD_NAME_CARDS_FIREBASE_DATABASE("cards"),
    CHILD_NAME_TRANSACTION("transaction");

    private String value;

    Symbol(String value){
        this.value = value;
    }

    public String GetValue(){
        return value;
    }
}
